# Generated by Django 3.2 on 2022-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_card',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
