# Generated by Django 3.2 on 2022-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_video_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_card',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
