# Generated by Django 3.2 on 2022-03-31 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('signature', models.ImageField(upload_to='signature/')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='team_image/')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_image/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_image', to='settings.about')),
            ],
            options={
                'verbose_name': 'Фото о нас',
                'verbose_name_plural': 'Фото о нас',
            },
        ),
    ]
